// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDtiUyi-Cr_SDCTypB8hiGHFjMh9cRMoA',
    appId: '1:237778016378:web:d9561fc86cb42e07a703c3',
    messagingSenderId: '237778016378',
    projectId: 'flutter-notification-ecd9b',
    authDomain: 'flutter-notification-ecd9b.firebaseapp.com',
    storageBucket: 'flutter-notification-ecd9b.appspot.com',
    measurementId: 'G-ZWNGHJ6P6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQUOPGhrqk4HRrxIcY-M2GRCtAqeu5rVw',
    appId: '1:237778016378:android:56e4fd640a83aa97a703c3',
    messagingSenderId: '237778016378',
    projectId: 'flutter-notification-ecd9b',
    storageBucket: 'flutter-notification-ecd9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhn3OBEDMuGPw4PustBA6vu5LsYyBBNN8',
    appId: '1:237778016378:ios:09a7338d4d0b1716a703c3',
    messagingSenderId: '237778016378',
    projectId: 'flutter-notification-ecd9b',
    storageBucket: 'flutter-notification-ecd9b.appspot.com',
    iosBundleId: 'com.example.notificationinfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhn3OBEDMuGPw4PustBA6vu5LsYyBBNN8',
    appId: '1:237778016378:ios:09a7338d4d0b1716a703c3',
    messagingSenderId: '237778016378',
    projectId: 'flutter-notification-ecd9b',
    storageBucket: 'flutter-notification-ecd9b.appspot.com',
    iosBundleId: 'com.example.notificationinfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDtiUyi-Cr_SDCTypB8hiGHFjMh9cRMoA',
    appId: '1:237778016378:web:1f764063e61bc2ada703c3',
    messagingSenderId: '237778016378',
    projectId: 'flutter-notification-ecd9b',
    authDomain: 'flutter-notification-ecd9b.firebaseapp.com',
    storageBucket: 'flutter-notification-ecd9b.appspot.com',
    measurementId: 'G-22FELVQX4Z',
  );
}
